#!/usr/bin/env bash
# Installs and configures HAproxy load balancer
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install -y haproxy
FRONTEND="frontend 471-lb-01\n\tbind *:80\n\tdefault_backend web-backend\n"
BACKEND="backend web-backend\n\tbalance roundrobin\n\tmode http\n\tserver 471-web-01 54.237.227.238 check\n\tserver 471-web-02 100.24.74.93 check\n"
sudo echo -e $FRONTEND >> /etc/haproxy/haproxy.cfg
sudo echo -e $BACKEND >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
