#!/usr/bin/env bash
# debugging nginx (service (init) must say that nginx is not running)
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx 
service nginx restart
# terminates the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
